# Generated by Django 4.0.6 on 2022-08-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_pupil',
            new_name='is_athlete',
        ),
    ]
