# Generated by Django 4.0.6 on 2022-08-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_profileathlete_athleteprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='aprovate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='aprovate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='aprovate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='aprovate',
            field=models.BooleanField(default=True),
        ),
    ]
