# Generated by Django 4.0.6 on 2022-08-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_athleteprofile_active_athleteprofile_aprovate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='groups')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('athletes', models.ManyToManyField(to='core.athleteprofile')),
                ('profesor_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professor_active', to='core.professorprofile')),
                ('professors', models.ManyToManyField(related_name='professors', to='core.professorprofile')),
            ],
        ),
    ]
