# Generated by Django 4.0.6 on 2022-08-02 01:53

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import examen_medico.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_athleteprofile_active_athleteprofile_aprovate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=examen_medico.models.image_directory_path)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_image_content_owner', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, core.utils.ResizeImageMixin),
        ),
        migrations.CreateModel(
            name='IMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athleteprofile')),
                ('imc_images', models.ManyToManyField(blank=True, related_name='imc_images', to='examen_medico.examimagecontent')),
                ('professor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.professorprofile')),
            ],
        ),
    ]
