# Generated by Django 4.0.6 on 2022-08-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_athleteprofile_active_athleteprofile_aprovate_and_more'),
        ('examen_medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imc',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professorprofile'),
        ),
    ]
